# Generated by Django 5.1.15 on 2026-09-03 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('APPLICATION_STATUS', 'Application Status Update'), ('NEW_APPLICATION', 'New Application Received'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('SYSTEM', 'System Alert')], default='SYSTEM', max_length=30)),
                ('link_url', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='idx_notif_user_read'), models.Index(fields=['created_at'], name='idx_notif_created_at')],
            },
        ),
    ]
