# Generated by Django 5.1.15 on 2026-09-03 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField(db_index=True)),
                ('duration_minutes', models.IntegerField(default=45)),
                ('interview_type', models.CharField(choices=[('TECHNICAL', 'Technical Interview'), ('HR', 'HR Interview'), ('BEHAVIORAL', 'Behavioral Interview')], default='TECHNICAL', max_length=20)),
                ('meeting_link_or_location', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled')], db_index=True, default='SCHEDULED', max_length=20)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='applications.application')),
            ],
            options={
                'verbose_name': 'Interview',
                'verbose_name_plural': 'Interviews',
                'ordering': ['scheduled_time'],
            },
        ),
    ]
